In [3]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:    
    print(x)
print(arr[1])

[1 2 3]
[4 5 6]
[4 5 6]


In [5]:
def vector(filename):
    # 创建向量
    returnVect = np.zeros((1, 8192))
    # print(returnVect)
    # 打开文件
    fr = open(filename)
    # 按行读取
    for i in range(8192):
        # 读一行数据
        lineStr = fr.readline().strip("\n")
        # print(lineStr)
        # 每一行的元素依次添加到returnVect中
        returnVect[0][i] = lineStr
    # 返回转换后的向量
    # print(returnVect)
    return returnVect

A=vector("../dataset/test1-test/10034-3")
print(A.shape)

(1, 8192)
